### ISSUE TITLE
Implementação teste: INSERINDO DADOS DO EXCEL NO BANCO DE DADOS com o bot no telegram. 

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-BOTO#52]
#### Objetivo? 
Testar a inserção de dados de uma planilha já preenchida no banco de dados  + um bot no telegram

#### Qual o problema?
Precisamos inserir os conteúdos que o professor utilizara através de uma planilha e no bot do professor. 

#### Tarefas // Critérios de aceitação
- [x] Fazer a implementação teste

#### Comentários 
[Vídeo Referencia](https://www.youtube.com/watch?v=61eUQ_qCGls&ab_channel=Dantasdc)
Pode ser em um bot teste não precisa ser no código do nosso bot

**Comment by TalesRG** [comment]
PR : https://github.com/fga-eps-mds/2022-2-BOTO/pull/60
