### ISSUE TITLE
Arrumar o épicos e features 

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-BOTO#54]
#### Objetivo? 
Fazer ajustes nos épicos pós feedback da professora.

#### Qual o problema?
Pós feedback da professora precisamos retirar algumas coisas e adicionar outras nos epicos e features.

#### Tarefas // Criterios de aceitação
- [x] Retirar o que não será mais feito
- [x] Adicionar o que será feito

#### Comentários 
---------------

**Comment by ananorberto** [comment]
### Arrumar o épicos e features #54

- Para acessar o link do Miro, clique [aqui](https://miro.com/app/board/uXjVPBhjaRg=/)
- Para ter acesso ao PDF - [Épicos, features e User stories.pdf](https://github.com/fga-eps-mds/2022-2-BOTO/files/10262086/Epicos.features.e.User.stories.pdf)
