### ISSUE TITLE
Mudanças no banco de dados 

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-BOTO#55]
#### Objetivo? 
Fazer algumas mudanças que percebemos que será necessário. 

#### Qual o problema?
Com a adição de um cadastro vários professores precisamos identificar qual dado e de qual professor.

#### Tarefas // Criterios de aceitação
- [ ] Tabela Professor
- [ ] Adição de novas colunas nas tabelas para identificação de qual professor ela pertence
- [ ] Colocar modela na pasta /docs do nosso github

#### Comentários 
---------------

**Comment by anafernanndess** [comment]
Create DATABASE BOTO;
USE BOTO;

CREATE TABLE professor(
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(50) NOT NULL,
plano_de_ensino VARCHAR(100) NOT NULL,
contato VARCHAR(30)
);

CREATE TABLE alunos(
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(50) NOT NULL,
matricula VARCHAR (12) NOT NULL,
fk_idProfessor int
);
alter table alunos
add foreign key(fk_idProfessor)
references professor(id);

CREATE TABLE conteudos(
id INT PRIMARY KEY AUTO_INCREMENT,
titulo VARCHAR(70) NOT NULL,
link VARCHAR(100) NOT NULL,
link_extra VARCHAR(100),
fk_idProfessor int
);
alter table conteudos
add foreign key(fk_idProfessor)
references professor(id);

INSERT INTO conteudos(titulo, link, link_extra) VALUES ('Números reais, naturais, inteiros, racionais e irracionais', 'https://www.todamateria.com.br/conjuntos-numericos/', null);
INSERT INTO conteudos(titulo, link, link_extra) VALUES ('Funções, modo de representar funções', 'https://www.matematica.pt/util/resumos/definir-representar-funcao.php', null);
INSERT INTO conteudos(titulo, link, link_extra) VALUES ('Limite e continuidade', 'https://youtu.be/DkCHV5Kbx4o', 'https://youtu.be/DIzwGegP8YE');
INSERT INTO conteudos(titulo, link, link_extra) VALUES ('Derivada', 'https://youtu.be/cWBEMN75IMc', 'https://educacionalplenus.com.br/exercicios-resolvidos-sobre-derivadas/');
INSERT INTO conteudos(titulo, link, link_extra) VALUES ('Aplicação da derivada', 'https://youtu.be/cJsJdXL3GOM', null);
INSERT INTO conteudos(titulo, link, link_extra) VALUES ('Integral', 'https://youtu.be/wkijt8-uxpY', null);
INSERT INTO conteudos(titulo, link, link_extra) VALUES ('Técnica de integração', 'https://youtu.be/nWEYwzzKLe8', 'https://pt.slideshare.net/DiegoOliveira462/exerccios-resolvidos-aplicao-da-integral');
INSERT INTO conteudos(titulo, link, link_extra) VALUES ('Aplicação da integral', 'https://youtu.be/PxMMtutKS8w', null);

CREATE TABLE conteudos_feitos(
id INT PRIMARY KEY AUTO_INCREMENT,
fk_idConteudo int,
fk_idAluno int
);
alter table conteudos_feitos
add foreign key(fk_idConteudo)
references conteudos(id);

alter table conteudos_feitos
add foreign key(fk_idAluno)
references alunos(id);


![image](https://user-images.githubusercontent.com/90392277/210291613-96cf6c53-61e0-4045-929a-141408989d6c.png)
