### ISSUE TITLE
Ajustar o protótipo do Professor e do Aluno

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-BOTO#56]
#### Objetivo? 
Fazer ajustes nos protótipos pós feedback da professora.

#### Qual o problema?
Pós feedback da professora precisamos retirar algumas coisas e adicionar outras no protótipo.

#### Tarefas // Criterios de aceitação
- [x] Retirar o que não será mais feito
- [x] Adicionar o que será feito

#### Comentários 
---------------

**Comment by Mylena-angelica** [comment]
Ajustes e alterações recebidas. O novo protótipo está em implementação

**Comment by Mylena-angelica** [comment]
Ajustes do aluno feitos!! 

Para melhor diferenciação, o nome do BOTO ficou "Botinho" para a versão do aluno.

[Link de revisão do protótipo- ALUNO](https://www.figma.com/file/jg8uxpnOEyLobSwp0HvG3e/Telegram-prototipo?node-id=280%3A529&t=fSJvwRIk1KS3NcSA-1)

**Comment by Mylena-angelica** [comment]
Ajustes do professor finalizado!!

[Link de revisão do protótipo- PROFESSOR](https://www.figma.com/file/jg8uxpnOEyLobSwp0HvG3e/Telegram-prototipo?node-id=280%3A3&t=fSJvwRIk1KS3NcSA-1)

**Comment by Mylena-angelica** [comment]
Por favor, @Beatrizvn 

Verificar se está tudo okay. 

Assim que tiver a sua resposta, adicionarei os novos links e arquivos no repositório
