### ISSUE TITLE
Fazer o  Issue Template  aparecer de novo

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-BOTO#57]
#### Objetivo? 
Fazer o aparecer de novo Issue Template.

#### Qual o problema?
Nosso issue template parou de aparecer nas opções e no Community Standards

#### Tarefas // Criterios de aceitação
- [ ] Fazer o aparecer de novo Issue Template.

#### Comentários 
---------------

**Comment by manuziny** [comment]
O issue temolate já está de volta e ativou o Community Standards novamente como solicitado.
