### ISSUE TITLE
Cadastro do professor no bot

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-BOTO#63]
#### Objetivo? 
O professor ter um cadastro no bot 

#### Qual o problema?
Precisamos diferenciar cada professor que irá utilizar o bot, por isso faremos um cadastro

#### Tarefas // Criterios de aceitação
- [x] Cadastro professor

#### Comentários 
----------------

**Comment by TalesRG** [comment]
##Backend cadastro/login professor
PR criada :https://github.com/fga-eps-mds/2022-2-BOTO/pull/85
