### ISSUE TITLE
Pesquisar sobre git action

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-BOTO#66]
#### Objetivo? 
Pesquisar sobre o git action

#### Tarefas // Criterios de aceitação
- [x] Fazer uma pesquisa sobre o git action
- [x] Colocar a pesquisa aqui

#### Comentários 
----------------

**Comment by ananorberto** [comment]
## GitHub Actions 

- Slide - [GitHub Actions.pdf](https://github.com/fga-eps-mds/2022-2-BOTO/files/10407595/GitHub.Actions.pdf)

**Referências**
- [Learn GitHub Actions](https://docs.github.com/pt/actions/learn-github-actions/finding-and-customizing-actions)
- [O que é o GitHub Actions?](https://www.cloudmotion.com.br/blog/2020/07/06/o-que-e-o-github-actions/)
- [GitHub Actions Tutorial and Examples](https://codefresh.io/learn/github-actions/github-actions-tutorial-and-examples/)
- [Github Actions— Everything You Need to Know to Get Started](https://towardsdatascience.com/github-actions-everything-you-need-to-know-to-get-started-537f1dffa0ed)
- [Criando um pipeline de CI/CD usando GitHub Actions](https://camargo-wes.medium.com/criando-um-pipeline-de-ci-cd-usando-github-actions-645a5199f650)
