### ISSUE TITLE
Teste unitarios

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-BOTO#74]
#### Objetivo? 
Fazer os testes unitarios das funções implementadas

#### Qual o problema?
Estamos com dificuldade de achar uma forma eficiente de fazer um teste unitario em um comando do bot.

#### Tarefas // Criterios de aceitação
- [x] Achar uma forma eficiente de fazer teste unitario em comando de bot

#### Comentários 
----------------

**Comment by Mylena-angelica** [comment]
Achei esse [repositório ](https://github.com/python-telegram-bot/python-telegram-bot)no git que pode ajudar a ter uma ideia de como fazer os testes.
