### ISSUE TITLE
Login Professor

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-BOTO#77]
#### Objetivo? 
Professor da login no bot

#### Qual o problema?
Se o professor der login ele não perderar suas informações caso apague o char no bot ou por algum motivo mude de dispositivo.

#### Tarefas // Criterios de aceitação
- [x] Login do professor

#### Comentários 
----------------

**Comment by anafernanndess** [comment]
https://github.com/fga-eps-mds/2022-2-BOTO/pull/100
