### ISSUE TITLE
Usar o codecov/coveralls 

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-BOTO#79]
#### Objetivo? 
Usar o codecov/coveralls para verificar a porcentagem de cobertura dos testes

#### Tarefas // Criterios de aceitação
- [x] Use o codecov/coveralls para verificar a porcentagem de cobertura dos testes

#### Comentários 
----------------

**Comment by Mylena-angelica** [comment]
Acredito que para fazer isso é necessário criar os testes primeiro

**Comment by Mylena-angelica** [comment]
Não consegui cadastrar o codecov. Não aparece para mim o nosso repositório

**Comment by manuziny** [comment]
Já dá pra usar ele nos testes que temos?

**Comment by Mylena-angelica** [comment]
Acredito que sim
