### ISSUE TITLE
Aluno receber os conteudos 

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-BOTO#90]
#### Objetivo? 
O aluno receber os conteudos que o professor colocou no banco de dados.

#### Tarefas // Criterios de aceitação
- [x] O aluno receber os conteudos

#### Comentários 
A lógica: 
![Flowchart](https://user-images.githubusercontent.com/73648297/213865211-c524a223-3d94-4573-97e8-5df5f4913780.jpg)

**Comment by manuziny** [comment]
O aluno já consegue receber os conteúdos como solicitado na issue.
