### ISSUE TITLE
Teste Unitarios

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-BOTO#95]
#### Objetivo? 
Fazer os testes unitarios cobrindo 90% das funções do código

#### Tarefas // Criterios de aceitação
- [x] Fazer os testes

#### Comentários 
Tentem começar pela parte do aluno, pois a parte do professor ainda tera algumas alterações essa semana.
Lembrem-se de todos darem commit.

**Comment by ananorberto** [comment]
### OBS: Fazendo os testes do boto_aluno
#
@Beatrizvn percebi a necessidade de uma simples alteração nas mensagens enviadas pelo bot, por exemplo o comando `/contatos_professor` e `/plano_de_ensino` não consta que deve ter a matrícula logo em seguida.

Posso fazer essa alteração?

**Comment by Beatrizvn** [comment]
> ### OBS: Fazendo os testes do boto_aluno
> #
> @Beatrizvn percebi a necessidade de uma simples alteração nas mensagens enviadas pelo bot, por exemplo o comando `/contatos_professor` e `/plano_de_ensino` não consta que deve ter a matrícula logo em seguida.
> 
> Posso fazer essa alteração?

@ananorberto Pode sim.
