### ISSUE TITLE
Testar o uso do bot completamente e verificar possiveis bugs

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-BOTO#98]
#### Objetivo? 
Verificar o uso do bot como um todo para resolver possiveis bugs.

#### Tarefas // Criterios de aceitação
- [x] Achar bugs
- [x] Resolver os bugs

#### Comentários 
----------------

**Comment by Mylena-angelica** [comment]
Testei aqui o bot do professsor pela main e funcionou certinho
